/**
 * ARD Comparison Tool
 * 
 * Standalone tool to compare test results against an Analytics Requirements Document (ARD).
 * 
 * Usage:
 *   node ard-compare.js --networkresults=./ga4-events-example.csv --ard=./ard.csv
 * 
 * Options:
 *   --networkresults=PATH    Path to the test results CSV file (generated by gtm-tracker.js)
 *   --ard=PATH              Path to the ARD CSV file
 *   --output=NAME           Optional custom output name (default: uses domain from results)
 * 
 * Examples:
 *   node ard-compare.js --networkresults=./ga4-events-example.com.csv --ard=./ard.csv
 *   node ard-compare.js --networkresults=./results.csv --ard=./ard.csv --output=my-comparison
 * 
 * @author AI Assistant
 * @version 1.0
 */

const fs = require('fs');
const path = require('path');
const ARDComparator = require('./utils/ard-comparator');
const CONFIG = require('./config/main');

// Parse command line arguments
const args = process.argv.slice(2);

let networkResultsPath = null;
let ardPath = null;
let customOutputName = null;

args.forEach(arg => {
  if (arg.startsWith('--networkresults=')) {
    networkResultsPath = arg.split('=')[1];
  } else if (arg.startsWith('--ard=')) {
    ardPath = arg.split('=')[1];
  } else if (arg.startsWith('--output=')) {
    customOutputName = arg.split('=')[1];
  }
});

// Validate arguments
if (!networkResultsPath || !ardPath) {
  console.log('❌ Missing required arguments\n');
  console.log('Usage: node ard-compare.js --networkresults=PATH --ard=PATH [--output=NAME]\n');
  console.log('📋 ARD Comparison Tool - Compare test results against ARD requirements\n');
  console.log('Required Arguments:');
  console.log('  --networkresults=PATH    Path to test results CSV (generated by gtm-tracker.js)');
  console.log('  --ard=PATH              Path to ARD CSV file\n');
  console.log('Optional Arguments:');
  console.log('  --output=NAME           Custom output filename (without extension)\n');
  console.log('Examples:');
  console.log('  node ard-compare.js --networkresults=./ga4-events-example.com.csv --ard=./ard.csv');
  console.log('  node ard-compare.js --networkresults=./results.csv --ard=./ard.csv --output=my-comparison\n');
  console.log('Output Files:');
  console.log('  - ard-compare-{name}.html   Visual comparison report');
  console.log('  - ard-compare-{name}.csv    Tabular comparison data');
  console.log('  - ard-compare-{name}.json   Machine-readable results\n');
  console.log('Configuration:');
  console.log('  Enable/disable report types in config/main.js → ARD_REPORT_GENERATION');
  process.exit(1);
}

// Check if files exist
if (!fs.existsSync(networkResultsPath)) {
  console.error(`❌ Network results file not found: ${networkResultsPath}`);
  process.exit(1);
}

if (!fs.existsSync(ardPath)) {
  console.error(`❌ ARD file not found: ${ardPath}`);
  process.exit(1);
}

// Determine output name
let outputName = customOutputName;
if (!outputName) {
  // Extract name from network results filename
  const basename = path.basename(networkResultsPath, path.extname(networkResultsPath));
  // If it's like "ga4-events-example.com", extract "example.com"
  const match = basename.match(/ga4-events-(.+)/);
  outputName = match ? match[1] : basename;
}

console.log('🔍 Starting ARD Comparison...\n');
console.log(`📊 Test Results: ${networkResultsPath}`);
console.log(`📋 ARD Document: ${ardPath}`);
console.log(`📝 Output Name: ${outputName}\n`);

// Check if ARD analysis is enabled in config
if (!CONFIG.ARD_ANALYSIS.enabled) {
  console.warn('⚠️  Warning: ARD_ANALYSIS.enabled is false in config/main.js');
  console.warn('   Continuing anyway as this is a standalone tool...\n');
}

try {
  // Load and compare
  const comparator = new ARDComparator();
  comparator.loadARD(ardPath);
  comparator.loadTestResults(networkResultsPath);
  
  console.log('🔄 Comparing results...\n');
  const comparisonResults = comparator.compare();
  
  // Display results summary
  console.log('📊 Comparison Results:');
  console.log('═══════════════════════════════════════════════════════');
  console.log(`   📈 Coverage:         ${comparisonResults.summary.coverage}%`);
  console.log(`   ✅ Matching:         ${comparisonResults.summary.matchingCount} events`);
  console.log(`   ❌ Missing:          ${comparisonResults.summary.missingCount} events`);
  console.log(`   ➕ Extra:            ${comparisonResults.summary.extraCount} events`);
  console.log(`   ⚠️  Mismatches:      ${comparisonResults.summary.parameterMismatchCount} events`);
  console.log(`   📋 Total ARD:        ${comparisonResults.summary.totalARDEvents} events`);
  console.log(`   🧪 Total Test:       ${comparisonResults.summary.totalTestEvents} events`);
  console.log('═══════════════════════════════════════════════════════\n');
  
  // Show details if there are issues
  if (comparisonResults.summary.missingCount > 0) {
    console.log('❌ Missing Events (in ARD but not found in test):');
    comparisonResults.missing.slice(0, 5).forEach((event, idx) => {
      console.log(`   ${idx + 1}. ${event.eventName}`);
    });
    if (comparisonResults.missing.length > 5) {
      console.log(`   ... and ${comparisonResults.missing.length - 5} more`);
    }
    console.log('');
  }
  
  if (comparisonResults.summary.parameterMismatchCount > 0) {
    console.log('⚠️  Parameter Mismatches (event found but parameters differ):');
    comparisonResults.parameterMismatch.slice(0, 5).forEach((event, idx) => {
      console.log(`   ${idx + 1}. ${event.eventName} - ${event.differences.length} parameter(s) differ`);
    });
    if (comparisonResults.parameterMismatch.length > 5) {
      console.log(`   ... and ${comparisonResults.parameterMismatch.length - 5} more`);
    }
    console.log('');
  }
  
  // Generate reports
  console.log('📝 Generating Reports...\n');
  
  // Create test-results directory if it doesn't exist
  const outputDir = path.join(__dirname, 'test-results');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  let generatedFiles = [];
  
  if (CONFIG.ARD_REPORT_GENERATION.html) {
    // Build site URL from output name (which contains the domain)
    // e.g., "network-events-www-neffy-com-..." -> "www.neffy.com"
    let siteUrl = outputName;
    
    // Try to extract domain from filename
    const domainMatch = outputName.match(/network-events-(.+?)-\d{4}-\d{2}-\d{2}/);
    if (domainMatch) {
      // Convert "www-neffy-com" to "www.neffy.com"
      const domain = domainMatch[1].replace(/-/g, '.');
      siteUrl = `https://${domain}`;
    } else if (!outputName.startsWith('http')) {
      siteUrl = `https://${outputName}`;
    }
    
    const htmlReport = comparator.generateHTMLReport(comparisonResults, siteUrl, networkResultsPath, ardPath);
    const htmlPath = path.join(outputDir, `ard-compare-${outputName}.html`);
    fs.writeFileSync(htmlPath, htmlReport);
    generatedFiles.push(htmlPath);
    console.log(`   ✅ HTML Report: ${path.relative(__dirname, htmlPath)}`);
  }
  
  if (CONFIG.ARD_REPORT_GENERATION.csv) {
    const csvReport = comparator.generateCSVReport(comparisonResults);
    const csvPath = path.join(outputDir, `ard-compare-${outputName}.csv`);
    fs.writeFileSync(csvPath, csvReport);
    generatedFiles.push(csvPath);
    console.log(`   ✅ CSV Report:  ${path.relative(__dirname, csvPath)}`);
  }
  
  if (CONFIG.ARD_REPORT_GENERATION.json) {
    const jsonReport = comparator.generateJSONReport(comparisonResults);
    const jsonPath = path.join(outputDir, `ard-compare-${outputName}.json`);
    fs.writeFileSync(jsonPath, jsonReport);
    generatedFiles.push(jsonPath);
    console.log(`   ✅ JSON Report: ${path.relative(__dirname, jsonPath)}`);
  }
  
  if (generatedFiles.length === 0) {
    console.log('   ⚠️  No reports generated (all report types disabled in config/main.js)');
  }
  
  console.log('\n✅ ARD Comparison completed successfully!');
  
  // Exit with appropriate code based on results
  if (comparisonResults.summary.missingCount > 0 || comparisonResults.summary.parameterMismatchCount > 0) {
    console.log('\n⚠️  Issues found - review the reports for details');
    process.exit(0); // Still exit 0 for successful comparison (just with issues)
  }
  
} catch (error) {
  console.error('\n❌ Error during ARD comparison:', error.message);
  console.error(error.stack);
  process.exit(1);
}

